# Generated by Django 3.1.7 on 2021-03-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BowserApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='address1',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Address line 1'),
        ),
        migrations.AddField(
            model_name='manager',
            name='address2',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Address line 2'),
        ),
        migrations.AddField(
            model_name='manager',
            name='company',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='manager',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AddField(
            model_name='manager',
            name='zip_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Postal code'),
        ),
    ]
