# Generated by Django 3.0.6 on 2021-03-05 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BowserApp', '0002_auto_20210305_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=10, unique=True, verbose_name='ID')),
                ('emp_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('emp_first_name', models.CharField(max_length=132, verbose_name='Last name')),
                ('emp_password', models.CharField(max_length=132, verbose_name='Password')),
                ('emp_address1', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Addess line 1')),
                ('emp_address2', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Addess line 2')),
                ('emp_zip_code', models.CharField(blank=True, max_length=12, null=True, verbose_name='Postal code')),
                ('emp_date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('emp_company', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Company Name')),
                ('emp_mobile_no', models.CharField(max_length=12, verbose_name='Mobile Number')),
                ('emp_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
