# Generated by Django 3.0.6 on 2021-03-05 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BowserApp', '0003_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('-emp_id',)},
        ),
    ]
