# Generated by Django 3.0.6 on 2021-03-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BowserApp', '0004_auto_20210305_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_city',
            field=models.CharField(blank=True, max_length=132, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_last_name',
            field=models.CharField(default='kumar', max_length=132, verbose_name='Last name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_first_name',
            field=models.CharField(max_length=132, verbose_name='First name'),
        ),
    ]
