# Generated by Django 3.0.6 on 2021-03-05 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BowserApp', '0005_auto_20210305_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
