# Generated by Django 3.1.7 on 2021-03-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BowserApp', '0006_auto_20210305_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
